// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrlqwcjrpeoqwkrhufhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhybHF3Y2pycGVvcXdrcmh1Zmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NzAyMjYsImV4cCI6MjA3MzI0NjIyNn0.DQIqkfMs3zxkbNm4xLGDpr8sQG7ZobsASjjhSBvwJzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});